Website/Controllers/GameController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Website.Models;
using Website.Services;

namespace Website.Controllers
{
    public class GameController : ControllerUserAware
    {

        private readonly IGamesService gamesService;
        public GameController(UserManager<UserModel> userManager, IGamesService gamesService): base(userManager) {
            this.gamesService = gamesService;
        }

        public async Task<IActionResult> Index()
        {
            var user = await CurrentUser;
            if (user == null) {
                return Unauthorized();
            }
            var game = await gamesService.GetGameOfUser(user.Id);
            return View();
        }
    
        public async Task<IActionResult> StartGame(Guid roomId)
        {
            await gamesService.CreateGameAsync(roomId, 0);

            return RedirectToAction("Index");
        }
    }
}

Website/Controllers/RoomsController.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Website.Models;
using Website.Services;

namespace Website.Controllers
{
    public class RoomsController: ControllerUserAware
    {
        private readonly IRoomsService roomsService;
        public RoomsController(UserManager<UserModel> userManager, IRoomsService roomsService): base(userManager) {
            this.roomsService = roomsService;
        }

        public async Task<IActionResult> Index() {
            var rooms = await roomsService.getAllRoomsAsync();

            var user = await CurrentUser;
            if (user != null) {
                rooms.CurrentUser = user;
            }
            
            return View(rooms);
        }

        public async Task<IActionResult> Create() {
            var user = await CurrentUser;
            if (user == null) {
                return Unauthorized();
            }
            await roomsService.CreateRoom(user.Id);

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Join(String roomToJoinId) {
            var user = await CurrentUser;
            if (user == null) {
                return Unauthorized();
            }
            await roomsService.AddUserToRoom(user.Id, roomToJoinId);

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Leave(String roomToLeaveId) {
            var user = await CurrentUser;
            if (user == null) {
                return Unauthorized();
            }
            
            await roomsService.RemoveUserFromRoom(user.Id, roomToLeaveId);

            return RedirectToAction("Index");
        }
    }
}

Website/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Website.Models;
using Website.Services;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Website.Data;

namespace Website.Controllers {
    public class UsersController: Controller {

        public UsersController(UserManager<UserModel> um, IUserService usersService) {
            _usersService = usersService;
            userManager = um;
            //userManager = new UserManager<IdentityUser>(new UserStore(context));
        }
        private readonly IUserService _usersService;
        private UserManager<UserModel> userManager;

        public IActionResult Index() {
            var model = new UserListModel() {
                Users = userManager.Users.ToList()
            };
           
            return View(model);
        }

    }
}

Website/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Website</title>

    <environment include="Development">
        <script src="~/dist/main.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="~/dist/main.js" asp-append-version="true"></script>
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Kasyno</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Game" asp-action="Index">Game</a></li>
                    <li><a asp-area="" asp-controller="Rooms" asp-action="Index">Rooms</a></li>
                    <li><a asp-area="" asp-controller="Users" asp-action="Index">Users</a></li>
                </ul>
                <partial name="_LoginPartial" />
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="body-content">
        @RenderBody()
        <hr />
        <footer class="text-center">
            <p>&copy; 2018 - Website</p>
        </footer>
    </div>

    @RenderSection("Scripts", required: false)
</body>
</html>